# Generated by Django 4.1.1 on 2022-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stand',
            name='picture',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
