# Generated by Django 4.1.1 on 2022-10-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_merchant_profile_pic_alter_stand_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='name',
            field=models.CharField(default='Apple Stand', max_length=255),
            preserve_default=False,
        ),
    ]
